#:import hex kivy.utils.get_color_from_hex
#:kivy 1.10.1
#:include navbar.kv
WindowManager:
    FirstWindow:
    ThirdWindow:
<FirstWindow>:
    name:"FirstWindow"
    Navbar:


<ThirdWindow>:
    name:"ThirdWindow"      
    anchorID:anchorID

    AnchorLayout:
        id:anchorID
        canvas.before:
            Color:
                rgba: .2, .2, .2, 1
            Rectangle:
                pos: self.pos
                size: self.size